import './globals.css'
import { Avatar, Box, Button, Link, Stack, Typography } from '@mui/material'
import { blue, red, grey } from '@mui/material/colors'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

const Header = () => {
  return (
    <Stack flexDirection={'row'}
      alignItems={'center'}
      justifyContent={'space-between'}
      sx={{ width: '100%', bgcolor: grey[900], padding: '10px 20px' }}>
      <Link href="/" underline='none'>
        <Typography variant='h5' color={grey[50]}>
          Cinema <strong>Clone</strong>
        </Typography>
      </Link>
      <Link href="/login">
        <Button sx={{ bgcolor: blue[800], textTransform: 'none', fontSize: '20px' }} variant="contained">Log in / Sign up</Button>
      </Link>
    </Stack>
  );
}

const Footer = () => {
  return (
    <Stack direction={'row'} spacing={'100px'} color={grey[50]} sx={{ width: '100%', height: '100%', bgcolor: grey[900], padding: '10px 20px' }}>
      <Stack direction={'row'} spacing={2} alignItems={'center'}>
        <Avatar
          alt="Cinema Clone"
          src="tv.png"
          sx={{ width: 56, height: 56 }}
        />
        <Typography variant='h5'>
          Cinema <strong>Clone</strong>
        </Typography>
      </Stack>
      <Stack direction={'row'} spacing={5}>
        <Stack>
          <Typography fontWeight={'bold'} mb={1} variant='h6'>
            ABOUT US
          </Typography>
          <ul>
            <li>21127147 - Võ Anh Quân</li>
            <li>21127188 - Đỗ Minh Triết</li>
          </ul>
        </Stack>
        <Stack>
          <Typography fontWeight={'bold'} mb={1} variant='h6'>
            RULES AND TERMS
          </Typography>
          <ul>
            <li>Membership Regulations</li>
            <li>Terms and Conditions</li>
            <li>Online Ticket Booking Guide</li>
            <li>General Rules and Policies</li>
            <li>Consumer Personal Information Protection Policy</li>
          </ul>
        </Stack>
        <Stack>
          <Typography fontWeight={'bold'} mb={1} variant='h6'>
            CUSTOMER SERVICE
          </Typography>
          <ul>
            <li>Hotline: 19002099</li>
            <li>Working Hours: 9:00 AM - 10:00 PM (Every day, including holidays and Tet)</li>
            <li>Support Email: cinemaClone@gmail.com</li>
          </ul>
        </Stack>
      </Stack>
    </Stack>
  );
}
